import scala.language.strictEquality

/** Currency represents one currency of the ISO_4217 currencies list
  * @see
  *   [[https://en.wikipedia.org/wiki/ISO_4217]]
  */
enum Currency(val numericCode: String) derives CanEqual {
  case AED extends Currency("784")
  case AFN extends Currency("971")
  case ALL extends Currency("008")
  case AMD extends Currency("051")
  case ANG extends Currency("532")
  case AOA extends Currency("973")
  case ARS extends Currency("032")
  case AUD extends Currency("036")
  case AWG extends Currency("533")
  case AZN extends Currency("944")
  case BAM extends Currency("977")
  case BBD extends Currency("052")
  case BDT extends Currency("050")
  case BGN extends Currency("975")
  case BHD extends Currency("048")
  case BIF extends Currency("108")
  case BMD extends Currency("060")
  case BND extends Currency("096")
  case BOB extends Currency("068")
  case BOV extends Currency("984")
  case BRL extends Currency("986")
  case BSD extends Currency("044")
  case BTN extends Currency("064")
  case BWP extends Currency("072")
  case BYN extends Currency("933")
  case BZD extends Currency("084")
  case CAD extends Currency("124")
  case CDF extends Currency("976")
  case CHE extends Currency("947")
  case CHF extends Currency("756")
  case CHW extends Currency("948")
  case CLF extends Currency("990")
  case CLP extends Currency("152")
  case CNY extends Currency("156")
  case COP extends Currency("170")
  case COU extends Currency("970")
  case CRC extends Currency("188")
  case CUC extends Currency("931")
  case CUP extends Currency("192")
  case CVE extends Currency("132")
  case CZK extends Currency("203")
  case DJF extends Currency("262")
  case DKK extends Currency("208")
  case DOP extends Currency("214")
  case DZD extends Currency("012")
  case EGP extends Currency("818")
  case ERN extends Currency("232")
  case ETB extends Currency("230")
  case EUR extends Currency("978")
  case FJD extends Currency("242")
  case FKP extends Currency("238")
  case GBP extends Currency("826")
  case GEL extends Currency("981")
  case GHS extends Currency("936")
  case GIP extends Currency("292")
  case GMD extends Currency("270")
  case GNF extends Currency("324")
  case GTQ extends Currency("320")
  case GYD extends Currency("328")
  case HKD extends Currency("344")
  case HNL extends Currency("340")
  case HRK extends Currency("191")
  case HTG extends Currency("332")
  case HUF extends Currency("348")
  case IDR extends Currency("360")
  case ILS extends Currency("376")
  case INR extends Currency("356")
  case IQD extends Currency("368")
  case IRR extends Currency("364")
  case ISK extends Currency("352")
  case JMD extends Currency("388")
  case JOD extends Currency("400")
  case JPY extends Currency("392")
  case KES extends Currency("404")
  case KGS extends Currency("417")
  case KHR extends Currency("116")
  case KMF extends Currency("174")
  case KPW extends Currency("408")
  case KRW extends Currency("410")
  case KWD extends Currency("414")
  case KYD extends Currency("136")
  case KZT extends Currency("398")
  case LAK extends Currency("418")
  case LBP extends Currency("422")
  case LKR extends Currency("144")
  case LRD extends Currency("430")
  case LSL extends Currency("426")
  case LYD extends Currency("434")
  case MAD extends Currency("504")
  case MDL extends Currency("498")
  case MGA extends Currency("969")
  case MKD extends Currency("807")
  case MMK extends Currency("104")
  case MNT extends Currency("496")
  case MOP extends Currency("446")
  case MRU extends Currency("929")
  case MUR extends Currency("480")
  case MVR extends Currency("462")
  case MWK extends Currency("454")
  case MXN extends Currency("484")
  case MXV extends Currency("979")
  case MYR extends Currency("458")
  case MZN extends Currency("943")
  case NAD extends Currency("516")
  case NGN extends Currency("566")
  case NIO extends Currency("558")
  case NOK extends Currency("578")
  case NPR extends Currency("524")
  case NZD extends Currency("554")
  case OMR extends Currency("512")
  case PAB extends Currency("590")
  case PEN extends Currency("604")
  case PGK extends Currency("598")
  case PHP extends Currency("608")
  case PKR extends Currency("586")
  case PLN extends Currency("985")
  case PYG extends Currency("600")
  case QAR extends Currency("634")
  case RON extends Currency("946")
  case RSD extends Currency("941")
  case RUB extends Currency("643")
  case RWF extends Currency("646")
  case SAR extends Currency("682")
  case SBD extends Currency("090")
  case SCR extends Currency("690")
  case SDG extends Currency("938")
  case SEK extends Currency("752")
  case SGD extends Currency("702")
  case SHP extends Currency("654")
  case SLL extends Currency("694")
  case SOS extends Currency("706")
  case SRD extends Currency("968")
  case SSP extends Currency("728")
  case STN extends Currency("930")
  case SVC extends Currency("222")
  case SYP extends Currency("760")
  case SZL extends Currency("748")
  case THB extends Currency("764")
  case TJS extends Currency("972")
  case TMT extends Currency("934")
  case TND extends Currency("788")
  case TOP extends Currency("776")
  case TRY extends Currency("949")
  case TTD extends Currency("780")
  case TWD extends Currency("901")
  case TZS extends Currency("834")
  case UAH extends Currency("980")
  case UGX extends Currency("800")
  case USD extends Currency("840")
  case USN extends Currency("997")
  case UYI extends Currency("940")
  case UYU extends Currency("858")
  case UYW extends Currency("927")
  case UZS extends Currency("860")
  case VES extends Currency("928")
  case VND extends Currency("704")
  case VUV extends Currency("548")
  case WST extends Currency("882")
  case XAF extends Currency("950")
  case XAG extends Currency("961")
  case XAU extends Currency("959")
  case XBA extends Currency("955")
  case XBB extends Currency("956")
  case XBC extends Currency("957")
  case XBD extends Currency("958")
  case XCD extends Currency("951")
  case XDR extends Currency("960")
  case XOF extends Currency("952")
  case XPD extends Currency("964")
  case XPF extends Currency("953")
  case XPT extends Currency("962")
  case XSU extends Currency("994")
  case XTS extends Currency("963")
  case XUA extends Currency("965")
  case XXX extends Currency("999")
  case YER extends Currency("886")
  case ZAR extends Currency("710")
  case ZMW extends Currency("967")
  case ZWL extends Currency("932")
}
import java.util.UUID

object UserId {
  opaque type Type = UUID

  def apply(value: UUID): Type = value
}
type UserId = UserId.Type

object OrderId {
  opaque type Type = UUID

  def apply(value: UUID): Type = value
}
type OrderId = OrderId.Type

opaque type LastName = String

object LastName {
  def apply(value: String): LastName = value
}
